name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.15 

    steps:
    - uses: actions/checkout@v2
    - name: Select xcode
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Lint the code
      run: swiftlint lint
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Build
      run: xcodebuild -scheme Animations-Package -destinations="platform=iOS Simulator,OS=14" -sdk iphonesimulator14.0 clean build 

