name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Lint the code
      run: swiftlint lint

  build-xc11_7:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Select xcode
      run: sudo xcode-select -s /Applications/Xcode_11.7.app
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Build on iOS
      run: xcodebuild -scheme Animations-Package -destination "platform=iOS Simulator,OS=13.7,name=iPhone 11 Pro" -sdk iphonesimulator13.7 clean build test
    - name: Build on tvOS
      run: xcodebuild -scheme Animations-Package -destination "platform=tvOS Simulator,OS=13.4,name=Apple TV 4K" -sdk appletvsimulator13.4 clean build test

  build-xc12:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Select xcode
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Build on iOS
      run: xcodebuild -scheme Animations-Package -destination "platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro" -sdk iphonesimulator14.0 clean build test
    - name: Build on tvOS
      run: xcodebuild -scheme Animations-Package -destination "platform=tvOS Simulator,OS=14.0,name=Apple TV 4K" -sdk appletvsimulator14.0 clean build test

  build-xc12_2-beta:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Select xcode
      run: sudo xcode-select -s /Applications/Xcode_12.2.app
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Build on iOS
      run: xcodebuild -scheme Animations-Package -destination "platform=iOS Simulator,OS=14.2,name=iPhone 12 mini" -sdk iphonesimulator14.2 clean build test
    - name: Build on tvOS
      run: xcodebuild -scheme Animations-Package -destination "platform=tvOS Simulator,OS=14.2,name=Apple TV 4K" -sdk appletvsimulator14.2 clean build test
